[package]
name = "mail-collector"
version = "0.10.1"
description = "A local-first multi-device mail client"
authors = ["OpenSpace"]
edition = "2021"

[lib]
name = "mail_collector_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
